ARG node=18

FROM node:${node}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y --no-install-recommends install wget git apt-transport-https lsb-release ca-certificates && \
    wget -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list && \
    apt-get -y update && \
    apt-get install -y --no-install-recommends curl openssh-client \
    nodejs yarn libpq-dev postgresql-client && apt-get clean && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && rm awscliv2.zip && \
    sh ./aws/install && rm -r ./aws && \
    useradd -m -d /home/ci -U -u 1000 ci

USER ci
