name: Build images

on:
  push:
    branches:
      - "gh-actions"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./laravel/php8.1/Dockerfile
            image: paneidos/debug
            tag: laravel-php8.2
            build-args: php=8.2,node=18
          - dockerfile: ./rails/ruby3.1/Dockerfile
            image: paneidos/debug
            tag: rails-ruby3.1
            build-args: ruby=3.2,node=18
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image }}:${{ matrix.tag }}
          build-args: ${{ matrix.build-args }}
